### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by miheerdew** [hungphamuy95/filter-adult-content#1]
I just found this project out (fresh out of the oven!). What does it do?

**Comment by hungphamuy95** [comment]
I am developing a chrome extension to hide all images that contain adult content in a specific forum

**Comment by miheerdew** [comment]
Cool. I was looking for an extension that hides such images everywhere. BTW, I found https://github.com/yahoo/open_nsfw interesting.

**Comment by hungphamuy95** [comment]
@miheerdew thanks you, i intend to use Microsoft Cognitive Service for recognizing adult content. Your suggestion looks like better so i am researching it right now.

**Comment by miheerdew** [comment]
Do you plan to keep it specific to a forum, or have it work everywhere? Would that make a difference?

**Comment by hungphamuy95** [comment]
It should work only for a specific forum. Actually, i want to learn reactjs so this repo is created for learning purpose. In the past, i developed a static html page using jquery to get and post data from Microsoft deep learning so i have some experiences on working with Cognitive Service API.

**Comment by miheerdew** [comment]
I see. Thanks.

**Comment by hungphamuy95** [comment]
You are welcome
